### ISSUE TITLE
What coordinate system is used in the heat map plots

### ISSUE THREAD

**Issue by msdrigg** [AeroSenseSw/AeroSenseAssure#3]
I am doing some tests with my assure device and I am having a hard time understanding what (x, y) refer to, and I didn't see anything in this repository that would clear that up. 

There are two possibilities that come to mind but I am not sure which one is correct (or if both are incorrect). Can someone clear up which is the real one?

Possibility 1:
<img width="1381" alt="Vertical" src="https://github.com/AeroSenseSw/AeroSenseAssure/assets/45189381/eecadfcf-9a6d-4ae3-bd3f-5eb4cd3fbc0f">

Possibility 2:
<img width="1381" alt="Horizontal" src="https://github.com/AeroSenseSw/AeroSenseAssure/assets/45189381/5c866c88-b81f-400d-8dc5-ea8df73345d4">

**Comment by alespour** [comment]
The coordinate system of data coming from the device (before X-axis transformation in the handler):
![axisxy](https://github.com/AeroSenseSw/AeroSenseAssure/assets/42931850/26857f08-b5c3-42e9-a25a-20ba0c9e6ee5)

**Comment by alespour** [comment]
Coordinate system of original data (ie. before the X-axis values transformation in the heatmap handler). XY are horizontal coords, where negative X values denote positions to the left of the "center" of the radar beam.
![288969134-eecadfcf-9a6d-4ae3-bd3f-5eb4cd3fbc0f](https://github.com/AeroSenseSw/AeroSenseAssure/assets/42931850/0d150c45-a38e-41e6-a7ad-9ecbdde30749)

**Comment by msdrigg** [comment]
Thank you!
